# Generated by Django 4.2 on 2023-07-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='pavadinimas',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='turinys',
        ),
    ]
