# Generated by Django 4.2 on 2023-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_post_pavadinimas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(default='default_photo.jpg', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='kategorija',
            field=models.ManyToManyField(to='blog.kategorija'),
        ),
    ]
