# Generated by Django 5.1.6 on 2025-02-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_foto_alter_post_turinys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
