# Generated by Django 4.2 on 2023-06-07 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Autorius',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Kategorija',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
