# Generated by Django 4.2 on 2023-06-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_author_autorius_rename_category_kategorija_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateArticleForm',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.article')),
            ],
            bases=('members.article',),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
