# Generated by Django 4.2 on 2023-07-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_id_article_auto_increment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateArticleForm',
        ),
    ]
