# Generated by Django 5.1.6 on 2025-02-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_delete_createarticleform"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article",
            new_name="Straipsnis",
        ),
    ]
