# Generated by Django 4.2 on 2023-05-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_options_parent_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
